stages:
  - build
  - test

build:ubuntu:
  image: elavram/ubuntu:latest
  stage: build
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y build-essential cmake git python3-dev python3-numpy
    - apt-get install -y lsb-core ocl-icd-opencl-dev pocl-opencl-icd
    - ldconfig
    - cd /builds/$CI_PROJECT_PATH
    - git submodule update --init
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build

test:ubuntu:
  image: elavram/ubuntu:latest
  stage: test
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y build-essential cmake git python3-dev python3-numpy
    - apt-get install -y lsb-core ocl-icd-opencl-dev pocl-opencl-icd
    - ldconfig
    - cd /builds/$CI_PROJECT_PATH/build/tests
    - ctest -V

build:fedora:
  image: fedora:latest
  stage: build
  tags:
    - docker
  script:
    - dnf install -y redhat-lsb-core dnf-plugins-core git cmake gcc g++ python3-devel.x86_64 python3-numpy
    - dnf -y copr enable jdanecki/intel-opencl
    - dnf install -y intel-opencl
    - dnf install -y ocl-icd ocl-icd-devel
    - cd /builds/$CI_PROJECT_PATH
    - git submodule update --init
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build

test:fedora:
  image: fedora:latest
  stage: test
  tags:
    - docker
  script:
    - dnf install -y redhat-lsb-core dnf-plugins-core git cmake gcc g++ python3-devel.x86_64 python3-numpy
    - dnf -y copr enable jdanecki/intel-opencl
    - dnf install -y intel-opencl
    - dnf install -y ocl-icd ocl-icd-devel
    - cd /builds/$CI_PROJECT_PATH/build/tests
    - ctest -V